// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJRTb_sUEwxBGNrJuZ5JaFKqVWqYs0APc',
    appId: '1:367947949128:web:c22d5bc41339653c2a247d',
    messagingSenderId: '367947949128',
    projectId: 'money-tracker-874b5',
    authDomain: 'money-tracker-874b5.firebaseapp.com',
    databaseURL: 'https://money-tracker-874b5-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-874b5.appspot.com',
    measurementId: 'G-KG24B8VDH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN5sv6WwWXuKImI06TugKFrGJCFufDEPE',
    appId: '1:367947949128:android:8bbb0878f536ff0c2a247d',
    messagingSenderId: '367947949128',
    projectId: 'money-tracker-874b5',
    databaseURL: 'https://money-tracker-874b5-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-874b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXtZ76f5mP5Ca1UYcrsogOBHdJpt17dZo',
    appId: '1:367947949128:ios:9a995c2c5f6aeed62a247d',
    messagingSenderId: '367947949128',
    projectId: 'money-tracker-874b5',
    databaseURL: 'https://money-tracker-874b5-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-874b5.appspot.com',
    iosClientId: '367947949128-e4b2l1ckudb9oqjhggoph78gtki189gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXtZ76f5mP5Ca1UYcrsogOBHdJpt17dZo',
    appId: '1:367947949128:ios:9a995c2c5f6aeed62a247d',
    messagingSenderId: '367947949128',
    projectId: 'money-tracker-874b5',
    databaseURL: 'https://money-tracker-874b5-default-rtdb.firebaseio.com',
    storageBucket: 'money-tracker-874b5.appspot.com',
    iosClientId: '367947949128-e4b2l1ckudb9oqjhggoph78gtki189gj.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTracker',
  );
}
